export { LegalFooter } from './components/LegalFooter'
export { LEGAL_PAGES, LEGAL_EFFECTIVE_DATE } from './config/legal-pages'
export type { LegalPageMeta } from './config/legal-pages'
export { TermsPage } from './pages/TermsPage'
export { PrivacyPage } from './pages/PrivacyPage'
export { RefundPage } from './pages/RefundPage'
export { DeliveryPage } from './pages/DeliveryPage'
export { ContactPage } from './pages/ContactPage'
export { BusinessTermsPage } from './pages/BusinessTermsPage'
