-- LedgerPro — One-shot migration: fold customers into users
--
-- WHEN TO RUN: Stop the backend, apply this SQL, then start the backend with
-- the new code. TypeORM's synchronize will see the schema already matches
-- the new entities and make no further changes.
--
-- WHAT IT DOES:
--   1. Adds CUSTOMER to the user_role enum.
--   2. Makes users.branch_id nullable (customers don't belong to a branch).
--   3. Adds users.phone column (migrated from customers.phone).
--   4. Copies every row from customers into users, PRESERVING UUIDs so the
--      customer_requests.customer_id values still reference the same identity.
--   5. Renames customer_requests.customer_id → user_id and re-points its FK
--      to users(id).
--   6. Drops the now-empty customers table.

BEGIN;

-- 1+2+3. Schema additions
ALTER TABLE users ALTER COLUMN branch_id DROP NOT NULL;

-- The enum type name follows TypeORM's auto-generated convention for a column
-- named "role" on the "users" table.
ALTER TYPE users_role_enum ADD VALUE IF NOT EXISTS 'customer';

ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR;

-- 4. Move customers → users
INSERT INTO users (
    id, email, password_hash, first_name, last_name, phone,
    role, branch_id, is_first_login,
    otp_code, otp_expires_at, is_verified, last_login_at,
    created_at, updated_at
)
SELECT
    id, email, password_hash, first_name, last_name, phone,
    'customer', NULL, false,
    otp_code, otp_expires_at, is_verified, last_login_at,
    created_at, updated_at
FROM customers
ON CONFLICT (email) DO NOTHING;  -- skip if a staff user already has that email

-- 5. Rename customer_requests.customer_id → user_id and re-point the FK.
-- The FK constraint name is auto-generated by TypeORM. Look it up first:
--     \d customer_requests
-- and replace the placeholder below with the actual constraint name.
DO $$
DECLARE
    fk_name text;
BEGIN
    SELECT con.conname INTO fk_name
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    WHERE rel.relname = 'customer_requests'
      AND con.contype = 'f'
      AND EXISTS (
          SELECT 1
          FROM unnest(con.conkey) attnum
          JOIN pg_attribute att ON att.attnum = attnum AND att.attrelid = rel.oid
          WHERE att.attname = 'customer_id'
      );

    IF fk_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE customer_requests DROP CONSTRAINT %I', fk_name);
    END IF;
END $$;

ALTER TABLE customer_requests RENAME COLUMN customer_id TO user_id;
ALTER TABLE customer_requests
    ADD CONSTRAINT "FK_customer_requests_user_id"
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;

-- 6. Drop the now-empty customers table.
DROP TABLE customers;

COMMIT;
