/**
 * LedgerPro — type barrel.
 * Each domain folder has its own index.ts that re-exports per-file types.
 * One interface / type per file under <domain>/<kebab-name>.type.ts.
 */
export * from './accounting'
export * from './admin'
export * from './analytics'
export * from './api'
export * from './auth'
export * from './branch'
export * from './brands'
export * from './category'
export * from './chat'
export * from './credit-accounts'
export * from './customer-orders'
export * from './customer-groups'
export * from './customers'
export * from './hr'
export * from './loyalty'
export * from './inventory'
export * from './notifications'
export * from './pos'
export * from './product'
export * from './purchases'
export * from './reviews'
export * from './shop'
export * from './shipments'
export * from './stock-transfers'
export * from './ui'
export * from './user'
