import type { TSupportedBaseUnit } from '@products/lib/supported-base-units';

export interface SupermarketProductSeed {
  name: string;
  barcode: string;
  category: string;
  /**
   * Canonical stock unit. Fixed-size packaged goods are counted as `unit`;
   * only loose weighted goods use `kg`, and loose liquids use `l`.
   */
  baseUnit: TSupportedBaseUnit;
  costPrice: number;
  sellingPrice: number;
  description: string;
}

export const SUPERMARKET_PRODUCTS: SupermarketProductSeed[] = [
  {
    name: 'Coca-Cola 1.5L Bottle',
    barcode: 'BVG-001',
    category: 'Beverages',
    baseUnit: 'unit',
    costPrice: 315,
    sellingPrice: 420,
    description: 'Classic Coca-Cola, 1.5 litre bottle',
  },
  {
    name: 'Pepsi 1.5L Bottle',
    barcode: 'BVG-002',
    category: 'Beverages',
    baseUnit: 'unit',
    costPrice: 315,
    sellingPrice: 420,
    description: 'Pepsi cola, 1.5 litre bottle',
  },
  {
    name: 'Sprite 1.5L Bottle',
    barcode: 'BVG-003',
    category: 'Beverages',
    baseUnit: 'unit',
    costPrice: 315,
    sellingPrice: 420,
    description: 'Sprite lemon-lime, 1.5 litre bottle',
  },
  {
    name: 'Orange Juice 1L Carton',
    barcode: 'BVG-004',
    category: 'Beverages',
    baseUnit: 'unit',
    costPrice: 840,
    sellingPrice: 1050,
    description: '100% pure orange juice, 1 litre carton',
  },
  {
    name: 'Bottled Water 1.5L',
    barcode: 'BVG-005',
    category: 'Beverages',
    baseUnit: 'unit',
    costPrice: 100,
    sellingPrice: 130,
    description: 'Spring water, 1.5 litre bottle',
  },
  {
    name: 'Tea Bags (100)',
    barcode: 'BVG-006',
    category: 'Beverages',
    baseUnit: 'unit',
    costPrice: 600,
    sellingPrice: 790,
    description: 'Black tea, 100-bag box',
  },
  {
    name: 'Instant Coffee 100g Jar',
    barcode: 'BVG-007',
    category: 'Beverages',
    baseUnit: 'unit',
    costPrice: 1320,
    sellingPrice: 1660,
    description: 'Instant coffee, 100g jar',
  },
  {
    name: 'Whole Milk 1L Carton',
    barcode: 'DRY-001',
    category: 'Dairy',
    baseUnit: 'unit',
    costPrice: 440,
    sellingPrice: 550,
    description: 'Fresh whole milk, 1 litre carton',
  },
  {
    name: 'Low-Fat Milk 1L Carton',
    barcode: 'DRY-002',
    category: 'Dairy',
    baseUnit: 'unit',
    costPrice: 416,
    sellingPrice: 520,
    description: 'Low-fat milk, 1 litre carton',
  },
  {
    name: 'Plain Yogurt 250g Cup',
    barcode: 'DRY-003',
    category: 'Dairy',
    baseUnit: 'unit',
    costPrice: 175,
    sellingPrice: 230,
    description: 'Plain yogurt, 250g cup',
  },
  {
    name: 'Salted Butter 250g Block',
    barcode: 'DRY-004',
    category: 'Dairy',
    baseUnit: 'unit',
    costPrice: 960,
    sellingPrice: 1200,
    description: 'Salted butter block, 250g',
  },
  {
    name: 'Cheddar Cheese 200g Block',
    barcode: 'DRY-005',
    category: 'Dairy',
    baseUnit: 'unit',
    costPrice: 840,
    sellingPrice: 1050,
    description: 'Cheddar cheese block, 200g',
  },
  {
    name: 'Eggs (12)',
    barcode: 'DRY-006',
    category: 'Dairy',
    baseUnit: 'unit',
    costPrice: 540,
    sellingPrice: 660,
    description: 'Free-range eggs, dozen',
  },
  {
    name: 'White Bread Loaf',
    barcode: 'BKY-001',
    category: 'Bakery',
    baseUnit: 'unit',
    costPrice: 340,
    sellingPrice: 450,
    description: 'Fresh white bread loaf, 700g',
  },
  {
    name: 'Brown Bread Loaf',
    barcode: 'BKY-002',
    category: 'Bakery',
    baseUnit: 'unit',
    costPrice: 390,
    sellingPrice: 520,
    description: 'Whole-wheat brown bread, 700g loaf',
  },
  {
    name: 'Burger Buns (6)',
    barcode: 'BKY-003',
    category: 'Bakery',
    baseUnit: 'unit',
    costPrice: 360,
    sellingPrice: 480,
    description: 'Soft burger buns, pack of 6',
  },
  {
    name: 'Dinner Rolls (8)',
    barcode: 'BKY-004',
    category: 'Bakery',
    baseUnit: 'unit',
    costPrice: 270,
    sellingPrice: 360,
    description: 'Dinner rolls, pack of 8',
  },
  {
    name: 'Apples',
    barcode: 'PRD-001',
    category: 'Produce',
    baseUnit: 'kg',
    costPrice: 800,
    sellingPrice: 1000,
    description: 'Loose red apples sold per KG',
  },
  {
    name: 'Bananas',
    barcode: 'PRD-002',
    category: 'Produce',
    baseUnit: 'kg',
    costPrice: 120,
    sellingPrice: 170,
    description: 'Loose Cavendish bananas sold per KG',
  },
  {
    name: 'Tomatoes',
    barcode: 'PRD-003',
    category: 'Produce',
    baseUnit: 'kg',
    costPrice: 350,
    sellingPrice: 490,
    description: 'Fresh loose tomatoes sold per KG',
  },
  {
    name: 'Onions',
    barcode: 'PRD-004',
    category: 'Produce',
    baseUnit: 'kg',
    costPrice: 180,
    sellingPrice: 260,
    description: 'Loose yellow onions sold per KG',
  },
  {
    name: 'Potatoes',
    barcode: 'PRD-005',
    category: 'Produce',
    baseUnit: 'kg',
    costPrice: 250,
    sellingPrice: 320,
    description: 'Loose potatoes sold per KG',
  },
  {
    name: 'Carrots',
    barcode: 'PRD-006',
    category: 'Produce',
    baseUnit: 'kg',
    costPrice: 270,
    sellingPrice: 360,
    description: 'Fresh loose carrots sold per KG',
  },
  {
    name: 'Basmati Rice 5kg Bag',
    barcode: 'PNT-001',
    category: 'Pantry',
    baseUnit: 'unit',
    costPrice: 4500,
    sellingPrice: 5500,
    description: 'Premium basmati rice, 5kg bag',
  },
  {
    name: 'Sugar 1kg Pack',
    barcode: 'PNT-002',
    category: 'Pantry',
    baseUnit: 'unit',
    costPrice: 220,
    sellingPrice: 295,
    description: 'White granulated sugar, 1kg pack',
  },
  {
    name: 'Iodized Salt 1kg Pack',
    barcode: 'PNT-003',
    category: 'Pantry',
    baseUnit: 'unit',
    costPrice: 240,
    sellingPrice: 315,
    description: 'Iodized table salt, 1kg pack',
  },
  {
    name: 'All-Purpose Flour 2kg Bag',
    barcode: 'PNT-004',
    category: 'Pantry',
    baseUnit: 'unit',
    costPrice: 360,
    sellingPrice: 490,
    description: 'All-purpose wheat flour, 2kg bag',
  },
  {
    name: 'Spaghetti Pasta 500g Pack',
    barcode: 'PNT-005',
    category: 'Pantry',
    baseUnit: 'unit',
    costPrice: 780,
    sellingPrice: 1000,
    description: 'Spaghetti pasta, 500g pack',
  },
  {
    name: 'Red Lentils 1kg Pack',
    barcode: 'PNT-006',
    category: 'Pantry',
    baseUnit: 'unit',
    costPrice: 220,
    sellingPrice: 280,
    description: 'Red lentils, 1kg pack',
  },
  {
    name: 'Loose Sunflower Oil',
    barcode: 'PNT-007',
    category: 'Pantry',
    baseUnit: 'l',
    costPrice: 1550,
    sellingPrice: 1925,
    description: 'Sunflower vegetable oil sold per L',
  },
  {
    name: 'Potato Chips 150g Bag',
    barcode: 'SNK-001',
    category: 'Snacks',
    baseUnit: 'unit',
    costPrice: 290,
    sellingPrice: 390,
    description: 'Salted potato chips, 150g bag',
  },
  {
    name: 'Chocolate Cookies 200g Pack',
    barcode: 'SNK-002',
    category: 'Snacks',
    baseUnit: 'unit',
    costPrice: 600,
    sellingPrice: 780,
    description: 'Chocolate chip cookies, 200g pack',
  },
  {
    name: 'Milk Chocolate Bar 100g',
    barcode: 'SNK-003',
    category: 'Snacks',
    baseUnit: 'unit',
    costPrice: 375,
    sellingPrice: 500,
    description: 'Milk chocolate bar, 100g',
  },
  {
    name: 'Salted Crackers 200g Pack',
    barcode: 'SNK-004',
    category: 'Snacks',
    baseUnit: 'unit',
    costPrice: 160,
    sellingPrice: 210,
    description: 'Salted crackers, 200g pack',
  },
  {
    name: 'Mixed Nuts 250g Jar',
    barcode: 'SNK-005',
    category: 'Snacks',
    baseUnit: 'unit',
    costPrice: 950,
    sellingPrice: 1250,
    description: 'Roasted mixed nuts, 250g jar',
  },
  {
    name: 'Frozen Chicken 1kg Pack',
    barcode: 'FRZ-001',
    category: 'Frozen',
    baseUnit: 'unit',
    costPrice: 1000,
    sellingPrice: 1250,
    description: 'Frozen chicken pieces, 1kg pack',
  },
  {
    name: 'Frozen Fish Fillet 500g Pack',
    barcode: 'FRZ-002',
    category: 'Frozen',
    baseUnit: 'unit',
    costPrice: 1750,
    sellingPrice: 2200,
    description: 'Frozen white fish fillet, 500g pack',
  },
  {
    name: 'Vanilla Ice Cream 1L Tub',
    barcode: 'FRZ-003',
    category: 'Frozen',
    baseUnit: 'unit',
    costPrice: 700,
    sellingPrice: 900,
    description: 'Vanilla ice cream, 1 litre tub',
  },
  {
    name: 'Dish Soap 500ml Bottle',
    barcode: 'HSH-001',
    category: 'Household',
    baseUnit: 'unit',
    costPrice: 320,
    sellingPrice: 425,
    description: 'Lemon dish soap, 500ml bottle',
  },
  {
    name: 'Laundry Detergent 1kg Bag',
    barcode: 'HSH-002',
    category: 'Household',
    baseUnit: 'unit',
    costPrice: 430,
    sellingPrice: 565,
    description: 'Powder laundry detergent, 1kg bag',
  },
  {
    name: 'Toilet Paper (12 rolls)',
    barcode: 'HSH-003',
    category: 'Household',
    baseUnit: 'unit',
    costPrice: 2500,
    sellingPrice: 3180,
    description: 'Toilet paper, 12-roll pack',
  },
  {
    name: 'Floor Cleaner 1L Bottle',
    barcode: 'HSH-004',
    category: 'Household',
    baseUnit: 'unit',
    costPrice: 530,
    sellingPrice: 700,
    description: 'Multi-surface floor cleaner, 1 litre bottle',
  },
  {
    name: 'Shampoo 400ml Bottle',
    barcode: 'PCR-001',
    category: 'Personal Care',
    baseUnit: 'unit',
    costPrice: 1150,
    sellingPrice: 1550,
    description: 'Anti-dandruff shampoo, 400ml bottle',
  },
  {
    name: 'Bath Soap Bar',
    barcode: 'PCR-002',
    category: 'Personal Care',
    baseUnit: 'unit',
    costPrice: 120,
    sellingPrice: 170,
    description: 'Moisturising bath soap, 100g bar',
  },
  {
    name: 'Toothpaste 100g Tube',
    barcode: 'PCR-003',
    category: 'Personal Care',
    baseUnit: 'unit',
    costPrice: 180,
    sellingPrice: 250,
    description: 'Mint fluoride toothpaste, 100g tube',
  },
  {
    name: 'Toothbrush',
    barcode: 'PCR-004',
    category: 'Personal Care',
    baseUnit: 'unit',
    costPrice: 100,
    sellingPrice: 150,
    description: 'Soft-bristle toothbrush',
  },
];

export const CATEGORY_THRESHOLDS: Record<string, number> = {
  Beverages: 30,
  Dairy: 30,
  Bakery: 25,
  Produce: 25,
  Pantry: 20,
  Snacks: 20,
  Frozen: 15,
  Household: 15,
  'Personal Care': 12,
};
